### ISSUE TITLE
No visible constructors Exception 

### ISSUE THREAD

**Issue by ThatGuy32** [nosan/embedded-cassandra#16]
Hi, it's me again

it looks like now it fails when starting with Spring Boot 2.0.4/Spring 5.0.8 
i guess Spring needs a Default Constructor (Maybe annotated with Autowired Annotation?)
not sure what i can do here 

here's the stack trace:

Caused by: java.lang.IllegalArgumentException: No visible constructors in class com.github.nosan.embedded.cassandra.spring.EmbeddedCassandraConfiguration$EmbeddedClusterFactoryBean
	at org.springframework.cglib.proxy.Enhancer.filterConstructors(Enhancer.java:666) ~[spring-core-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.cglib.proxy.Enhancer.generateClass(Enhancer.java:567) ~[spring-core-5.0.8.RELEASE.jar:5.0.8.RELEASE]

**Comment by ThatGuy32** [comment]
looks like i can't reproduce it on a smaller project either
i reverted back to 2.1.0.M2 and it works again

**Comment by nosan** [comment]
weird, `FactoryBean` doesn't have a constructor at all.
Currently, I close this one, but still, if you would be able to reproduce this issue, please let me know.

Thanks

**Comment by ThatGuy32** [comment]
okay, will :)
