### ISSUE TITLE
Cassandra 4.x doesn't work on Windows

### ISSUE THREAD

**Issue by Traderjoe95** [nosan/embedded-cassandra#173]
I have tried using Cassandra 4.0-beta4 with embedded-cassandra 4.0.1 on Windows 10 which fails giving the following error:

```
com.kobil.ssms.ast.storage.lib.CassandraStorageTest *** ABORTED ***
  com.github.nosan.embedded.cassandra.CassandraException: Unable to await: DefaultCassandra{name='cassandra-0', version='4.0-beta4'}
  at com.github.nosan.embedded.cassandra.DefaultCassandra.await(DefaultCassandra.java:257)
  at com.github.nosan.embedded.cassandra.DefaultCassandra.start(DefaultCassandra.java:97)
  at com.kobil.ssms.ast.storage.lib.CassandraStorageTest.beforeAll(CassandraStorageTest.scala:32)
  at org.scalatest.BeforeAndAfterAll.liftedTree1$1(BeforeAndAfterAll.scala:212)
  at org.scalatest.BeforeAndAfterAll.run(BeforeAndAfterAll.scala:210)
  at org.scalatest.BeforeAndAfterAll.run$(BeforeAndAfterAll.scala:208)
  at com.kobil.ssms.ast.storage.lib.CassandraStorageTest.run(CassandraStorageTest.scala:25)
  at org.scalatest.Suite.callExecuteOnSuite$1(Suite.scala:1175)
  at org.scalatest.Suite.$anonfun$runNestedSuites$1(Suite.scala:1222)
  at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
  ...
  Cause: java.io.IOException: 'WindowsCassandraDatabase{process=Process[pid=9552, exitValue=1]}' is not alive. Please see logs for more details.

Errors:

C:\Users\JOHANN~1.LEU\AppData\Local\Temp\apache-cassandra-4.0-beta4-8590206010260606935\bin\cassandra.ps1 : The term 
'C:\Users\JOHANN~1.LEU\AppData\Local\Temp\apache-cassandra-4.0-beta4-8590206010260606935\bin\cassandra.ps1' is not recognized as the name of a cmdlet, function, script file, or operable
```

This is most definitely caused by the `cassandra.ps1` script not being part of the 4.0-beta4 package.

I suppose this is not under your control, but the incompatibility should be at least documented. At the moment, the documentation states that embedded-cassandra supports Windows, MacOS and Linux (Ubuntu) **AND** Cassandra versions 2.x-4.x. I hope for a solution for that problem in the future, but for now I understand that it is impossible to fix.

**Comment by nosan** [comment]
Hi @Traderjoe95,
Unfortunately, the Apache Cassandra team decided to stop supporting Windows `*.ps` and `*.bat` scripts.

Right now, it is documented in this section:
https://nosan.github.io/embedded-cassandra/4.0.1/#version

But I think you are right and it also should be documented in this section as well.
https://nosan.github.io/embedded-cassandra/4.0.1/#what-are-versions-supported-by-embedded-cassandra

**Comment by nosan** [comment]
fixed: https://github.com/nosan/embedded-cassandra/commit/8ffb813f92afed68e97f74bec130ed2a0ccaf753

feel free to open PR if you have something in your mind about how documentation can be upgraded.
