### ISSUE TITLE
Multiple test case run throwing error

### ISSUE THREAD

**Issue by SayantaBankBazaar** [nosan/embedded-cassandra#175]
A single test case is working fine, the same test case is throwing the following error when running with multiple test cases.
Tried different stable cassandra versions but facing the same issue.

`Caused by: com.github.nosan.embedded.cassandra.CassandraException: Unable to await: DefaultCassandra{name='cassandra-0', version='4.0-beta4'}
	at com.github.nosan.embedded.cassandra.DefaultCassandra.await(DefaultCassandra.java:257)
	at com.github.nosan.embedded.cassandra.DefaultCassandra.start(DefaultCassandra.java:97)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeCustomInitMethod(AbstractAutowireCapableBeanFactory.java:1914)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1856)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1784)
	... 148 common frames omitted
Caused by: java.io.IOException: 'UnixCassandraDatabase{process=java.lang.UNIXProcess@397fac68}' is not alive. Please see logs for more details.
`

Using embedded-cassandra-spring-boot-starter 4.x.x with yaml:

> #Cassandra config file.
cassandra.embedded.config-file=classpath:cu-cassandra.yaml
#Config properties, that should be merged with properties from cassandra.yaml.
cassandra.embedded.config-properties.native_transport_port=9042
#Cassandra environment variables.
cassandra.embedded.environment-variables.JAVA_HOME=${JAVA8_HOME}
#Logger name, that consumes Cassandra STDOUT and STDERR outputs.
cassandra.embedded.logger=Cassandra
#Cassandra instance name.
cassandra.embedded.name=cassandra-0
#Sets if the created Cassandra should have a shutdown hook registered.
cassandra.embedded.register-shutdown-hook=true
#Startup timeout.
cassandra.embedded.startup-timeout=2m
#Cassandra native Java Virtual Machine (JVM) system parameters.
cassandra.embedded.system-properties.[cassandra.jmx.local.port]=7199
#Cassandra working directory.
cassandra.embedded.working-directory=target/cassandra-latest-version
#Additional resources, that should be copied into the working directory.
cassandra.embedded.working-directory-resources.[conf/cassandra.yaml]=classpath:cu-cassandra.yaml

**Comment by nosan** [comment]
Hi @SayantaBankBazaar,
it is not related to Embedded Cassandra itself, it happens because of Spring Test ApplicationContext caching. In order to fix this, you can just add `@DirtiesContext` annotation.

https://docs.spring.io/spring-framework/docs/current/reference/html/testing.html#spring-testing-annotation-dirtiescontext
