### ISSUE TITLE
Does not working on Windows 10

### ISSUE THREAD

**Issue by eugenediatlov** [nosan/embedded-cassandra#250]
macOS/Linux - works perfectly.
Win 10 failure: file .\bin\cassandra.ps1 is not included in Cassandra binary package

Logs:
c:\Projects\1>java -jar ./configurator-1.0.0-SNAPSHOT.jar
Mar 14, 2022 6:23:30 PM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @2045a718'

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.2.1.RELEASE)

2022-03-14 18:23:31.170  INFO 4592 --- [JavaFX-Launcher] o.s.boot.SpringApplication               : Starting application on Win10 with PID 4592 (C:\Projects\1\configurator-1.0.0-SNAPSHOT.jar started by jey in c:\Projects\1)
2022-03-14 18:23:31.173  INFO 4592 --- [JavaFX-Launcher] o.s.boot.SpringApplication               : No active profile set, falling back to default profiles: default
2022-03-14 18:23:31.810  INFO 4592 --- [JavaFX-Launcher] o.s.boot.SpringApplication               : Started application in 0.991 seconds (JVM running for 1.804)
2022-03-14 18:23:34.095  INFO 4592 --- [       Thread-4] c.g.n.e.c.WebCassandraDirectoryProvider  : Cassandra directory: 'C:\Users\jey\.embedded-cassandra\cassandra\4.0-rc1\apache-cassandra-4.0-rc1' is not found. Initializing...
2022-03-14 18:23:34.097  INFO 4592 --- [       Thread-4] c.g.n.e.c.WebCassandraDirectoryProvider  : Acquires a lock to the file 'C:\Users\jey\.embedded-cassandra\cassandra\4.0-rc1\.lock'...
2022-03-14 18:23:35.512  INFO 4592 --- [       Thread-4] c.g.n.e.c.WebCassandraDirectoryProvider  : Downloading Apache Cassandra: '4.0-rc1' from URI: 'https://archive.apache.org/dist/cassandra/4.0-rc1/apache-cassandra-4.0-rc1-bin.tar.gz'. It takes a while...
2022-03-14 18:23:36.867  INFO 4592 --- [       Thread-4] c.g.n.e.c.WebCassandraDirectoryProvider  : 4,653,056 / 46,519,925 10%
2022-03-14 18:23:37.597  INFO 4592 --- [       Thread-4] c.g.n.e.c.WebCassandraDirectoryProvider  : 9,306,112 / 46,519,925 20%
2022-03-14 18:23:38.071  INFO 4592 --- [       Thread-4] c.g.n.e.c.WebCassandraDirectoryProvider  : 13,959,168 / 46,519,925 30%
2022-03-14 18:23:38.549  INFO 4592 --- [       Thread-4] c.g.n.e.c.WebCassandraDirectoryProvider  : 18,612,224 / 46,519,925 40%
2022-03-14 18:23:39.045  INFO 4592 --- [       Thread-4] c.g.n.e.c.WebCassandraDirectoryProvider  : 23,265,280 / 46,519,925 50%
2022-03-14 18:23:39.530  INFO 4592 --- [       Thread-4] c.g.n.e.c.WebCassandraDirectoryProvider  : 27,918,336 / 46,519,925 60%
2022-03-14 18:23:40.005  INFO 4592 --- [       Thread-4] c.g.n.e.c.WebCassandraDirectoryProvider  : 32,571,392 / 46,519,925 70%
2022-03-14 18:23:40.450  INFO 4592 --- [       Thread-4] c.g.n.e.c.WebCassandraDirectoryProvider  : 37,216,256 / 46,519,925 80%
2022-03-14 18:23:40.966  INFO 4592 --- [       Thread-4] c.g.n.e.c.WebCassandraDirectoryProvider  : 41,869,312 / 46,519,925 90%
2022-03-14 18:23:41.475  INFO 4592 --- [       Thread-4] c.g.n.e.c.WebCassandraDirectoryProvider  : 46,519,925 / 46,519,925 100%
2022-03-14 18:23:41.475  INFO 4592 --- [       Thread-4] c.g.n.e.c.WebCassandraDirectoryProvider  : Verifying checksum...
2022-03-14 18:23:41.646  INFO 4592 --- [       Thread-4] c.g.n.e.c.WebCassandraDirectoryProvider  : Checksums are identical
2022-03-14 18:23:41.647  INFO 4592 --- [       Thread-4] c.g.n.e.c.WebCassandraDirectoryProvider  : Extracting...
2022-03-14 18:23:42.295  INFO 4592 --- [       Thread-4] c.g.n.e.c.WebCassandraDirectoryProvider  : Cassandra directory: 'C:\Users\jey\.embedded-cassandra\cassandra\4.0-rc1\apache-cassandra-4.0-rc1' is initialized.
2022-03-14 18:23:42.554  INFO 4592 --- [       Thread-4] c.g.n.e.c.WindowsCassandraDatabase       : [cassandra-0] powershell -ExecutionPolicy Unrestricted c:\Projects\1\database\bin\cassandra.ps1 -p c:\Projects\1\database\bin\9925787920985091157-cassandra.pid -a -f
2022-03-14 18:23:42.786 ERROR 4592 --- [ssandra.ps1:ERR] c.g.nosan.embedded.cassandra.Cassandra   : c:\Projects\1\database\bin\cassandra.ps1 : The term 'c:\Projects\1\database\bin\cassandra.ps1' is not recognized as
2022-03-14 18:23:42.786 ERROR 4592 --- [ssandra.ps1:ERR] c.g.nosan.embedded.cassandra.Cassandra   : the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was
2022-03-14 18:23:42.788 ERROR 4592 --- [ssandra.ps1:ERR] c.g.nosan.embedded.cassandra.Cassandra   : included, verify that the path is correct and try again.
2022-03-14 18:23:42.788 ERROR 4592 --- [ssandra.ps1:ERR] c.g.nosan.embedded.cassandra.Cassandra   : At line:1 char:1
2022-03-14 18:23:42.788 ERROR 4592 --- [ssandra.ps1:ERR] c.g.nosan.embedded.cassandra.Cassandra   : + c:\Projects\1\database\bin\cassandra.ps1 -p c:\Projects\1\database\bi ...
2022-03-14 18:23:42.789 ERROR 4592 --- [ssandra.ps1:ERR] c.g.nosan.embedded.cassandra.Cassandra   : + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2022-03-14 18:23:42.789 ERROR 4592 --- [ssandra.ps1:ERR] c.g.nosan.embedded.cassandra.Cassandra   :     + CategoryInfo          : ObjectNotFound: (c:\Projects\1\database\bin\cassandra.ps1:String) [], CommandNotFoundExc
2022-03-14 18:23:42.789 ERROR 4592 --- [ssandra.ps1:ERR] c.g.nosan.embedded.cassandra.Cassandra   :    eption
2022-03-14 18:23:42.790 ERROR 4592 --- [ssandra.ps1:ERR] c.g.nosan.embedded.cassandra.Cassandra   :     + FullyQualifiedErrorId : CommandNotFoundException
2022-03-14 18:23:42.790 ERROR 4592 --- [ssandra.ps1:ERR] c.g.nosan.embedded.cassandra.Cassandra   :
Exception in thread "Thread-4" com.github.nosan.embedded.cassandra.CassandraException: Unable to await DefaultCassandra{name='cassandra-0', version='4.0-rc1'}. Caused by: java.io.IOException: 'WindowsCassandraDatabase{process=Process[pid=5616, exitValue=1]}' is not alive. Please see logs for more details.
Errors:
c:\Projects\1\database\bin\cassandra.ps1 : The term 'c:\Projects\1\database\bin\cassandra.ps1' is not recognized as
the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was
included, verify that the path is correct and try again.
At line:1 char:1
+ c:\Projects\1\database\bin\cassandra.ps1 -p c:\Projects\1\database\bi ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (c:\Projects\1\database\bin\cassandra.ps1:String) [], CommandNotFoundExc
   eption
    + FullyQualifiedErrorId : CommandNotFoundException

Output:

        at com.github.nosan.embedded.cassandra.DefaultCassandra.await(DefaultCassandra.java:261)
        at com.github.nosan.embedded.cassandra.DefaultCassandra.start(DefaultCassandra.java:97)
        at com.partizan.ims.configurator.SetupClusterController.startCassandra(SetupClusterController.java:122)
        at com.partizan.ims.configurator.SetupClusterController.run(SetupClusterController.java:67)
        at com.partizan.ims.configurator.MainController.lambda$newInstallation$0(MainController.java:43)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.io.IOException: 'WindowsCassandraDatabase{process=Process[pid=5616, exitValue=1]}' is not alive. Please see logs for more details.
Errors:
c:\Projects\1\database\bin\cassandra.ps1 : The term 'c:\Projects\1\database\bin\cassandra.ps1' is not recognized as
the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was
included, verify that the path is correct and try again.
At line:1 char:1
+ c:\Projects\1\database\bin\cassandra.ps1 -p c:\Projects\1\database\bi ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (c:\Projects\1\database\bin\cassandra.ps1:String) [], CommandNotFoundExc
   eption
    + FullyQualifiedErrorId : CommandNotFoundException

Output:

        at com.github.nosan.embedded.cassandra.DefaultCassandra.await(DefaultCassandra.java:235)
        ... 5 more

**Comment by nosan** [comment]
Unfortunately, since Cassandra 4.0-beta4, Windows support was completely removed by Apache Cassandra team.

**Comment by eugenediatlov** [comment]
Wow. Got it.
