### ISSUE TITLE
Unable to start embedded cassandra using JDK11

### ISSUE THREAD

**Issue by kamat66** [nosan/embedded-cassandra#322]
I get following error when I start embedded cassandra using 

            Cassandra cassandra = new CassandraBuilder().build();
            cassandra.start();

I'm using JDK11.

com.github.nosan.embedded.cassandra.CassandraException: Unable to start DefaultCassandra{name='cassandra-0', version='4.0.3'}. Caused by: java.io.FileNotFoundException: C:\Users\<user.home>\AppData\Local\Temp\2496137276350945222\bin\cassandra.ps1 does not exist

	at com.github.nosan.embedded.cassandra.DefaultCassandra.doStart(DefaultCassandra.java:177)
	at com.github.nosan.embedded.cassandra.DefaultCassandra.start(DefaultCassandra.java:96)
	at com.cpc.track.service.track.dao.cassandra.CassandraTrackDaoTest.setup(CassandraTrackDaoTest.java:44)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:514)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:178)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
Caused by: java.io.FileNotFoundException: C:\Users\vaibhav_kamat\AppData\Local\Temp\2496137276350945222\bin\cassandra.ps1 does not exist
	at com.github.nosan.embedded.cassandra.WindowsCassandraDatabase.assertFileExists(WindowsCassandraDatabase.java:202)
	at com.github.nosan.embedded.cassandra.WindowsCassandraDatabase.startServerPowershell(WindowsCassandraDatabase.java:103)
	at com.github.nosan.embedded.cassandra.WindowsCassandraDatabase.startServer(WindowsCassandraDatabase.java:88)
	at com.github.nosan.embedded.cassandra.WindowsCassandraDatabase.doStart(WindowsCassandraDatabase.java:50)
	at com.github.nosan.embedded.cassandra.AbstractCassandraDatabase.start(AbstractCassandraDatabase.java:65)
	at com.github.nosan.embedded.cassandra.DefaultCassandra.doStart(DefaultCassandra.java:167)
	... 25 more
	Suppressed: java.io.FileNotFoundException: C:\Users\<user.home>\AppData\Local\Temp\2496137276350945222\bin\cassandra.bat does not exist
		at com.github.nosan.embedded.cassandra.WindowsCassandraDatabase.assertFileExists(WindowsCassandraDatabase.java:202)
		at com.github.nosan.embedded.cassandra.WindowsCassandraDatabase.startServerBat(WindowsCassandraDatabase.java:121)
		at com.github.nosan.embedded.cassandra.WindowsCassandraDatabase.startServer(WindowsCassandraDatabase.java:92)
		... 28 more

**Comment by nosan** [comment]
Hello, 

https://nosan.github.io/embedded-cassandra/4.0.7/#what-are-versions-supported-by-embedded-cassandra


Apache Cassandra team deleted all scripts for windows platform. 

You can use testcontainers

**Comment by kamat66** [comment]
Thank you for your response.
