### ISSUE TITLE
Embedded Cassandra 3.1.0 would not start with JDK 11

### ISSUE THREAD

**Issue by kamat66** [nosan/embedded-cassandra#323]
I used below dependency to use 3.1.0 with JDK 11

<dependency>
                <groupId>com.github.nosan</groupId>
                <artifactId>embedded-cassandra-testng-test</artifactId>
                <version>3.1.0</version>
            </dependency>

and used 

			Cassandra cassandra = getCassandra();
			CassandraConnection cassandraConnection = getCassandraConnection();

in a testNG setup()

I get below error when I start

2023-05-31 11:45:17,105 INFO [cassandra-1] c.g.n.e.c.a.Cassandra Cassandra 3.0 and later require Java 8u40 or later.

com.github.nosan.embedded.cassandra.api.CassandraException: Unable to start EmbeddedCassandra[name='cassandra-1', version='3.11.9']

	at com.github.nosan.embedded.cassandra.EmbeddedCassandra.doStart(EmbeddedCassandra.java:151)
	at com.github.nosan.embedded.cassandra.EmbeddedCassandra.start(EmbeddedCassandra.java:64)
	at com.github.nosan.embedded.cassandra.testng.AbstractCassandraTests.startCassandra(AbstractCassandraTests.java:205)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:514)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:178)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
Caused by: java.io.IOException: 'WindowsCassandraNode[pid='19612', exitValue='0']' is not alive. Please see logs for more details
	Cassandra 3.0 and later require Java 8u40 or later.
	*---------------------------------------------------------------------*
	*---------------------------------------------------------------------*
	    Modify conf\cassandra.env.ps1 to suppress this warning.
	    Performance of this node will suffer.
	    WARNING! Detected a power profile other than High Performance.
	*---------------------------------------------------------------------*
	*---------------------------------------------------------------------*
	Failed 64-bit check. Re-running to get version from 32-bit
	*---------------------------------------------------------------------*
	*---------------------------------------------------------------------*
	    for performance and stability reasons.
	    It is recommended that you disable swap when running Cassandra
	    WARNING!  Automatic page file configuration detected.
	*---------------------------------------------------------------------*
	*---------------------------------------------------------------------*
	at com.github.nosan.embedded.cassandra.EmbeddedCassandraDatabase.await(EmbeddedCassandraDatabase.java:239)
	at com.github.nosan.embedded.cassandra.EmbeddedCassandraDatabase.start(EmbeddedCassandraDatabase.java:118)
	at com.github.nosan.embedded.cassandra.EmbeddedCassandra.doStart(EmbeddedCassandra.java:145)
	... 25 more

**Comment by nosan** [comment]
Apache Cassandra 3.x.x requires jdk 1.8

>Cassandra 3.0 and later require Java 8u40 or later.

**Comment by nosan** [comment]
You can use the latest Embedded Cassandra version and just set the correct version of Apache Cassandra.

`new CassandraBuilder().version(..).build()`

But remember that Apache Cassandra 3.x.x supports only jdk 1.8, and Apache Cassandra 4.x.x supports jdk11.

**Comment by kamat66** [comment]
Thanks Nosan for all the help.
