### ISSUE TITLE
Unable to start Embedded Cassandra

### ISSUE THREAD

**Issue by JAffa097** [nosan/embedded-cassandra#330]
Hi , I am trying to start embedded cassandra in my local with default properties. But I am getting below error.
Exception in thread "main" com.github.nosan.embedded.cassandra.CassandraException: Unable to start DefaultCassandra{name='cassandra-0', version='4.0.3'}. Caused by: java.io.FileNotFoundException: C:\Users\KRISHN~1\AppData\Local\Temp\6511994450052980900\bin\cassandra.ps1 does not exist
	at com.github.nosan.embedded.cassandra.DefaultCassandra.doStart(DefaultCassandra.java:177)
	at com.github.nosan.embedded.cassandra.DefaultCassandra.start(DefaultCassandra.java:96)
	at org.example.Main.main(Main.java:16)
Caused by: java.io.FileNotFoundException: C:\Users\KRISHN~1\AppData\Local\Temp\6511994450052980900\bin\cassandra.ps1 does not exist
	at com.github.nosan.embedded.cassandra.WindowsCassandraDatabase.assertFileExists(WindowsCassandraDatabase.java:202)
	at com.github.nosan.embedded.cassandra.WindowsCassandraDatabase.startServerPowershell(WindowsCassandraDatabase.java:103)
	at com.github.nosan.embedded.cassandra.WindowsCassandraDatabase.startServer(WindowsCassandraDatabase.java:88)
	at com.github.nosan.embedded.cassandra.WindowsCassandraDatabase.doStart(WindowsCassandraDatabase.java:50)
	at com.github.nosan.embedded.cassandra.AbstractCassandraDatabase.start(AbstractCassandraDatabase.java:65)
	at com.github.nosan.embedded.cassandra.DefaultCassandra.doStart(DefaultCassandra.java:167)
	... 2 more
	Suppressed: java.io.FileNotFoundException: C:\Users\KRISHN~1\AppData\Local\Temp\6511994450052980900\bin\cassandra.bat does not exist
		at com.github.nosan.embedded.cassandra.WindowsCassandraDatabase.assertFileExists(WindowsCassandraDatabase.java:202)
		at com.github.nosan.embedded.cassandra.WindowsCassandraDatabase.startServerBat(WindowsCassandraDatabase.java:121)
		at com.github.nosan.embedded.cassandra.WindowsCassandraDatabase.startServer(WindowsCassandraDatabase.java:92)
		... 5 more

My CODE : public static void main(String[] args) {

        Cassandra cassandra = new CassandraBuilder().build();
        cassandra.start();
        try {
            Settings settings = cassandra.getSettings();
            try (CqlSession session = CqlSession.builder()
                    .addContactPoint(new InetSocketAddress(settings.getAddress(), settings.getPort()))
                    .withLocalDatacenter("datacenter1")
                    .build()) {
                CqlScript.ofClassPath("schema.cql").forEachStatement(session::execute);
            }
        }
        finally {
            cassandra.stop();
        }
        System.out.println("Hello world!");
    }

**Comment by nosan** [comment]
Hello, Apache Cassandra since 4.x has stopped supporting Windows OS and removed all related powershell scripts.
