### ISSUE TITLE
Would not start due to SecurityManager deprecation with jdk 21

### ISSUE THREAD

**Issue by govindbalaji-s** [nosan/embedded-cassandra#381]
`DefaultCassandra.start()` gives below exception:

```
ERROR [main] 2024-02-27 20:08:26,984 CassandraDaemon.java:897 - Exception encountered during startup
java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
	at java.base/java.lang.System.setSecurityManager(System.java:429)
	at org.apache.cassandra.security.ThreadAwareSecurityManager.install(ThreadAwareSecurityManager.java:96)
	at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:248)
	at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:751)
	at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:875)
	at com.github.nosan.embedded.cassandra.DefaultCassandra.await(DefaultCassandra.java:261)
	at com.github.nosan.embedded.cassandra.DefaultCassandra.start(DefaultCassandra.java:97)
```
https://openjdk.org/jeps/411

**Comment by govindbalaji-s** [comment]
This works around for now `CassandraBuilder.addSystemProperty("java.security.manager", "allow")`

**Comment by nosan** [comment]
Thanks @govindbalaji-s 
Once Apache Cassandra 5.0 is released I will take a look at what can be done.

**Comment by nosan** [comment]
Added to the documentation about this issue. Thanks.
