### ISSUE TITLE
Cql scripts are executed before Cassandra is ready

### ISSUE THREAD

**Issue by smiklosovic** [nosan/embedded-cassandra#68]
I am using Junit4 ClassRule and I am seeing this issue:

```
[2020-03-06 18:07:24] [main] INFO  c.g.n.e.cassandra.EmbeddedCassandra - EmbeddedCassandra[name='cassandra-1', version='3.11.6'] has been started and ready for connections!
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 4.881 sec <<< FAILURE!
mypackageandclass  Time elapsed: 4.881 sec  <<< ERROR!
com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (no host was tried)
        at com.datastax.driver.core.exceptions.NoHostAvailableException.copy(NoHostAvailableException.java:84)
        at com.datastax.driver.core.exceptions.NoHostAvailableException.copy(NoHostAvailableException.java:37)
        at com.datastax.driver.core.DriverThrowables.propagateCause(DriverThrowables.java:37)
        at com.datastax.driver.core.DefaultResultSetFuture.getUninterruptibly(DefaultResultSetFuture.java:245)
        at com.datastax.driver.core.AbstractSession.execute(AbstractSession.java:68)
        at com.datastax.driver.core.AbstractSession.execute(AbstractSession.java:43)
        at com.github.nosan.embedded.cassandra.api.connection.ClusterCassandraConnection.execute(ClusterCassandraConnection.java:52)
        at com.github.nosan.embedded.cassandra.api.connection.ClusterCassandraConnection.execute(ClusterCassandraConnection.java:33)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1082)
        at com.github.nosan.embedded.cassandra.junit4.test.CassandraRule.before(CassandraRule.java:219)
        at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:46)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)


```

My rule looks like this:

```
    public static final CassandraRule TEST_CASSANDRA_RULE = new CassandraRule(cassandraFactory -> {
        cassandraFactory.setArtifact(Artifact.ofVersion(Version.of("3.11.6")));
        cassandraFactory.getJvmOptions().add("-Xmx1g");
        cassandraFactory.getJvmOptions().add("-Xms1g");
        cassandraFactory.setPort(9042);
    }).withCqlDataSet(CqlDataSet.ofClasspaths("persistence/ddl.cql"));
```

I am on 3.11.6 and 3.0.2 version of this library.

**Comment by smiklosovic** [comment]
All good, I was running with Spring so I used Spring integration and that issue was resolved. Strange.
